package Vista;


import Modelo.MesaMod;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;



public class Mesa extends javax.swing.JFrame {
    

    private JButton[][] botones; // Declaración de la matriz de botones como variable de instancia
    private MesaMod mesa;
    
    public Mesa() {
        initComponents();
        int filas = 5; // Número de filas en la matriz
        int columnas =5; // Número de columnas en la matriz
        setResizable(false);
        

        jPanel1.setLayout(new GridLayout(filas, columnas));

        botones = new JButton[filas][columnas]; // Inicialización de la matriz de botones
        mesa = new MesaMod ();
        for (int i = 0; i < filas; i++) { 
            for (int j = 0; j < columnas; j++) {
                botones[i][j] = new JButton(); // Crea un nuevo botón
                botones[i][j] = new JButton("M" + (i * columnas + j + 1)); 
                int numeroMesa = i * columnas + j + 1;
                //ImageIcon icono = new ImageIcon("C:\\Users\\aleja\\Documents\\Files Alejandra\\Proyecto2\\ModuloSalon\\src\\main\\java\\Vista\\Imagenes\\mesa.png");
              //  botones[i][j].setIcon(icono);
                botones[i][j].setBackground(Color.WHITE);
                botones[i][j].setMaximumSize(new Dimension(Short.MAX_VALUE, Short.MAX_VALUE)); // Establecer tamaño máximo del botón

                botones[i][j].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Guardar la información de la mesa en la clase mesa del modelo
                         mesa.guardarInfoMesa(numeroMesa);
                         dispose();// cierra la ventana al presionar el boton
                    }
                });              
                jPanel1.add(botones[i][j]); // Agrega el botón al panel
            }
        }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mesa().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables





}
