/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Salon.ordenC;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;

/**
 *
 * @author Llermy
 */
public class ventanaSalon extends javax.swing.JFrame {

    /**
     * Creates new form ventanaSalon
     */
    
    JButton[][] botonesMesas;
    ordenC matrizOrdPedidos[][] = new ordenC[5][5];
    public static String mensajeComPedido;
    public static int filas;
    public static int columnas;
    
    
    public ventanaSalon() {
        initComponents();
        
        crearBotPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotonesMesas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Salon del restaurante.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBotonesMesasLayout = new javax.swing.GroupLayout(panelBotonesMesas);
        panelBotonesMesas.setLayout(panelBotonesMesasLayout);
        panelBotonesMesasLayout.setHorizontalGroup(
            panelBotonesMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBotonesMesasLayout.setVerticalGroup(
            panelBotonesMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBotonesMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaSalon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel panelBotonesMesas;
    // End of variables declaration//GEN-END:variables

    public void crearBotPedidos(){ 
        
       filas = 5; // Número de filas en la matriz
       columnas =5; // Número de columnas en la matriz
        
        
        panelBotonesMesas.setLayout(new GridLayout(filas, columnas));

        botonesMesas = new JButton[filas][columnas]; // Inicialización de la matriz de botones
        for (int i = 0; i < filas; i++) { 
            for (int j = 0; j < columnas; j++) {
                botonesMesas[i][j] = new JButton(); // Crea un nuevo botón
                botonesMesas[i][j] = new JButton("Mesa "+ (i * columnas + j + 1)); 
                //botonesMesas[i][j].addActionListener(this);
                //botonesMesas[i][j] = null;//llena la mtriz para la info de los pedidos
                botonesMesas[i][j].setBackground(Color.WHITE);
                botonesMesas[i][j].setPreferredSize(new Dimension(50, 50)); // Establece el ancho y alto deseados
                panelBotonesMesas.add(botonesMesas[i][j]); // Agrega el botón al panel
            }
        } 
        
    }
    
    public void cambiarBoton(ordenC tempPed, int tempI, int tempJ){
        Color nuevoColor ;//= Color.RED; // Color deseado para el botón
        if (tempPed == null){
            nuevoColor = Color.WHITE;
        }
        else{
            nuevoColor = Color.RED;
        }
        botonesMesas[tempI][tempJ].setBackground(nuevoColor); // Cambia el color del botón específico
        matrizOrdPedidos[tempI][tempJ] = tempPed;
    }
    
     public void actionPerformed(ActionEvent e) {   // Al presionar el boton de la matriz de botones de la mesa 
        JButton sourceButton = (JButton) e.getSource();

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (sourceButton == botonesMesas[i][j]) {
                    if (matrizOrdPedidos[i][j] != null){
                        //numMesa = i * columnas + j + 1;
                        //mensajeComPedido = "Pedido de la mesa " + numMesa; // listo lo calcula bien
                        //cambiarBoton(mensajeComPedido, i,j);
                        //ventanaCompPedido tempVentana = new ventanaCompPedido(matrizStrPedidos[i][j],this, tempSocket, i, j);
                        //tempVentana.setVisible(true);
                        System.out.println("el pido por ver es:");
                        System.out.println(matrizOrdPedidos[i][j].pasarOrdenToString());
                    }
                    
                    break; // Termina el bucle una vez que se encuentra el botón presionado
                }
            }
        }
    }

}
